[package]
name = "wlroots-extra-protocols"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wayland-backend = "0.3.4"
wayland-client = "0.31.3"
wayland-scanner = "0.31.2"
