[package]
name = "tawaylon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vosk = "0.2.0"
wayland-protocols = {version = "0.32", features = ["unstable"] }
wayland-protocols-wlr = "0.3"

